spring:
  datasource:
    url: jdbc:mysql://39.108.13.46:3306/fengsy?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Fengsy.win
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode:
      LEGACYHTML5

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rcz.entity